name: Deploy to Linux Server

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Write SSH private key to file
      run: |
        echo "${{ secrets.SERVER_SSH_KEY }}" > id_rsa
        chmod 600 id_rsa

    - name: Copy files to server using SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key_path: ./id_rsa
        port: 55000
        source: "."
        target: "/home/${{ secrets.SERVER_USER }}/interceptionInjection"
        exclude: "id_rsa"

    - name: Delete SSH private key
      run: rm -f id_rsa
