name: SSH B64 Test

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Decode private key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY_B64 }}" | base64 -d > id_rsa
          chmod 600 id_rsa

      - name: Test SSH connection
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key_path: ./id_rsa
          port: 55000
          script: |
            echo "✅ SSH connection successful!"
